# Generated by Django 2.2.11 on 2020-04-04 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cno', models.CharField(max_length=10)),
                ('cname', models.CharField(max_length=4)),
                ('ccredit', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.CharField(max_length=10)),
                ('sname', models.CharField(max_length=10)),
                ('sage', models.IntegerField(default=0)),
                ('spassward', models.CharField(max_length=20)),
                ('ssex', models.BooleanField(choices=[(0, '男'), (1, '女')], max_length=1)),
                ('sdept', models.CharField(max_length=10)),
                ('swhere', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tno', models.CharField(max_length=10)),
                ('tname', models.CharField(max_length=4)),
                ('tage', models.IntegerField(default=0)),
                ('tpassward', models.CharField(max_length=20)),
                ('tsex', models.BooleanField(choices=[(0, '男'), (1, '女')], max_length=1)),
                ('tdept', models.CharField(max_length=10)),
                ('trank', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='TC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classno', models.CharField(max_length=10)),
                ('cno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestModel.Course')),
                ('tno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestModel.Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='SC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(default=0)),
                ('classno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestModel.TC')),
                ('cno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestModel.Course')),
                ('sno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestModel.Student')),
            ],
        ),
    ]
