# Generated by Django 2.2.11 on 2020-04-04 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0003_auto_20200404_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='ssex',
            field=models.CharField(max_length=10),
        ),
    ]
