# Generated by Django 2.2.11 on 2020-04-04 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0004_auto_20200404_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='tname',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='tsex',
            field=models.CharField(max_length=10),
        ),
    ]
