# Generated by Django 2.2.11 on 2020-04-04 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0005_auto_20200404_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='trank',
            field=models.CharField(max_length=20),
        ),
    ]
