# Generated by Django 2.2.11 on 2020-04-08 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0007_auto_20200407_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sc',
            name='classno',
        ),
        migrations.RemoveField(
            model_name='tc',
            name='classno',
        ),
    ]
